;
delete from events_txt;
INSERT INTO events_txt (id, code, text, id_language) VALUES (25, 36, 'Operating mode has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (24, 34, 'Mode pressure for device has been changed successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (23, 33, 'State of valve has been changed successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (21, 31, 'Cycle Time of vaporiser has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (20, 30, 'Pumping Time to set value has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (22, 32, 'On Time On of vaporiser has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (19, 29, 'Wait time for confirmation of change state of fore pump has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (18, 28, 'State of fore pump has been changed successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (15, 25, 'Max current for power supply has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (13, 23, 'Max voltage for power supply has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (12, 22, 'Voltage limit for power supply has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (10, 20, 'Power limit for power supply has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (9, 19, 'Operating state for power supply has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (8, 18, 'Working mode for power supply has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (7, 17, 'Setpoint for power supply has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (6, 16, 'Pressure setpoint has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (4, 11, 'Flow for MFC has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (3, 10, 'Time for flow stabilisation has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (2, 9, 'Voltage Range for MFC has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (1, 8, 'Max flow for MFC has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (11, 21, 'Current limit for power supply has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (16, 26, 'Wait time for confirmation of power supply set operation has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (17, 27, 'Wait time on stabilisation setpoint for power supply has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (26, 38, 'Dosing value for vaporiser has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (27, 39, 'Type of vaporiser valve has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (28, 40, 'Activity that corresponding MFC has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (29, 41, 'Pressure stabilisation time for process PID has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (30, 42, 'One of PID parameters has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (14, 24, 'Max power for power supply has been set successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (5, 12, 'Settings have been read successfully.', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (38, 50, 'State of gas controller has been set successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (31, 43, 'Date/time of PLC has been set successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (39, 51, 'Pressure limit for safe working of power supply has been set successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (35, 47, 'Leak test parameters have been updated successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (40, 52, 'Pressure limit for gas injection has been set successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (36, 48, 'Leak test has been stopped successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (34, 46, 'Number of processes and whole working time of machine has been cleared successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (33, 45, 'Whole working time of pump has been cleared successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (32, 44, 'Leak test has been started successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (37, 49, 'State of motor control has been changed successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (41, 53, 'Gauge factor for gas in chamber has been set successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (42, 54, 'Type of gas flow by MFC has been set successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (43, 55, 'Type of calibrated gas for MFC has been set successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (44, 56, 'Threshold of gas mixture protection procedure has been set successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (45, 57, 'State of  gas mixture protection procedure has been set successfully', 2);
INSERT INTO events_txt (id, code, text, id_language) VALUES (46, 58, 'Stabilisation time for flow of gas mixture protection procedure has been set successfully', 2);